language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip
  - pip install flake8 flake8-import-order

script:
  - python setup.py test
  - flake8 .
